[tool.poetry]
name = "commentary-capsule"
version = "0.1.0"
description = "A project to gather reviews, comments, and other sources of text feedback for classification and identification"
authors = ["progressEdd"]
license = "GNU AFFERO GENERAL PUBLIC LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ipykernel = "^6.29.5"
pandas = "^2.2.2"
openpyxl = "^3.1.5"
numpy = "^2.0.1"
playwright = "^1.46.0"
openai = "^1.41.0"
requests = "^2.32.3"
tqdm = "^4.66.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
